In [124]:
import pandas as pd 
import numpy as np

In [125]:
movies_df = pd.read_csv('data/movies.csv') 
credits_df = pd.read_csv('data/credits.csv')

In [126]:
credits_df.head()

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [127]:
movies_df.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",10-12-2009,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",19-05-2007,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bondâ€™s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",26-10-2015,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",16-07-2012,1084939099,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",07-03-2012,284139100,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124

In [128]:
movies_df.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",10-12-2009,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",19-05-2007,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bondâ€™s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",26-10-2015,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",16-07-2012,1084939099,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",07-03-2012,284139100,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124

In [129]:
credits_df.head()

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [130]:
#merging datasets
movies_df=movies_df.merge(credits_df,on='title')

In [131]:
movies_df.shape

(4808, 23)

In [132]:
movies_df.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,movie_id,cast,crew
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,19995,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...",...,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500,285,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bondâ€™s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...",...,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466,206647,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...",...,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106,49026,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]",...,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124,49529,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [133]:
movies_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4808 entries, 0 to 4807
Data columns (total 23 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   budget                4808 non-null   int64
 1   genres                4808 non-null   object
 2   homepage              1713 non-null   object
 3   id                    4808 non-null   int64
 4   keywords              4808 non-null   object
 5   original_language     4808 non-null   object
 6   original_title        4808 non-null   object
 7   overview              4805 non-null   object
 8   popularity            4808 non-null   float64
 9   production_companies  4808 non-null   object
 10  production_countries  4808 non-null   object
 11  release_date          4807 non-null   object
 12  revenue               4808 non-null   int64
 13  runtime               4806 non-null   float64
 14  spoken_languages      4808 non-null   object
 15  status                4808 non-null   object
 16  tagline               3964 non-null   object
 17  title                 4808 non-null   object
 18  vote_average          4808 non-null   float64
 19  vote_count            4808 non-null   int64
 20  movie_id              4808 non-null   int64
 21  cast                  4808 non-null   object
 22  crew                  4808 non-null   object
dtypes: float64(3), int64(5), object(15)
memory usage: 864.1+ KB

In [134]:
movies_df= movies_df[['movie_id','title','overview','genres','keywords','cast','crew']]

In [135]:
movies_df.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bondâ€™s past sends him o...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [136]:
movies_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4808 entries, 0 to 4807
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   movie_id  4808 non-null   int64
 1   title     4808 non-null   object
 2   overview  4805 non-null   object
 3   genres    4808 non-null   object
 4   keywords  4808 non-null   object
 5   cast      4808 non-null   object
 6   crew      4808 non-null   object
dtypes: int64(1), object(6)
memory usage: 263.1+ KB

In [137]:
movies_df.isnull().sum()

movie_id    0
title       0
overview    3
genres      0
keywords    0
cast        0
crew        0
dtype: int64

In [138]:
movies_df.dropna(inplace=True)

In [139]:
movies_df.duplicated().sum()

0

In [140]:
movies_df.iloc[0].genres

'[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'

In [141]:
import ast

In [142]:
def convert(obj):
    L=[]
    for i in ast.literal_eval(obj):
        L.append(i['name'])
    return L

In [143]:
movies_df['genres']=movies_df['genres'].apply(convert)
movies_df['keywords']=movies_df['keywords'].apply(convert)
movies_df.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bondâ€™s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [144]:
def conert3(obj):
    L=[]
    counter = 0
    for i in ast.literal_eval(obj):
        if counter !=3:
            L.append(i['name'])
            counter +=1
        else:
            break
        return L

In [145]:
movies_df.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bondâ€™s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [146]:
def fetch_director(obj):
    L=[]
    for i in ast.literal_eval(obj):
        if i['job']=='Director':
            L.append(i['name'])
    return L

In [147]:
movies_df['crew'] = movies_df['crew'].apply(fetch_director)

In [148]:
movies_df

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...",[James Cameron]
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...",[Gore Verbinski]
2,206647,Spectre,A cryptic message from Bondâ€™s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...",[Sam Mendes]
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...",[Christopher Nolan]
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...",[Andrew Stanton]
...,...,...,...,...,...,...,...
4803,9367,El Mariachi,El Mariachi just wants to play his guitar and ...,"[Action, Crime, Thriller]","[united statesâ€“mexico barrier, legs, arms, pap...","[{""cast_id"": 1, ""character"": ""El Mariachi"", ""c...",[Robert Rodriguez]
4804,72766,Newlyweds,A newlywed couple's honeymoon is upended by th...,"[Comedy, Romance]",[],"[{""cast_id"": 1, ""character"": ""Buzzy"", ""credit_...",[Edward Burns]
4805,231617,"Signed, Sealed, Delivered","""Signed, Sealed, Delivered"" introduces a dedic...","[Comedy, Drama, Romance, TV Movie]","[date, love at first sight, narration, investi...","[{""cast_id"": 8, ""character"": ""Oliver O\u2019To...",[Scott Smith]
4806,126186,Shanghai Calling,When ambitious New York attorney Sam is sent t...,[],[],"[{""cast_id"": 3, ""character"": ""Sam"", ""credit_id...",[Daniel Hsia]
4807,25975,My Date with Drew,Ever since the second grade when he first saw ...,[Documentary],"[obsession, camcorder, crush, dream girl]","[{""cast_id"": 3, ""character"": ""Herself"", ""credi...","[Brian Herzlinger, Jon Gunn, Brett Winn]"

In [149]:
movies_df['overview'][0]

'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization.'

In [150]:
movies_df['overview']=movies_df['overview'].apply(lambda x:x.split())

In [151]:
movies_df

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...",[James Cameron]
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...",[Gore Verbinski]
2,206647,Spectre,"[A, cryptic, message, from, Bondâ€™s, past, send...","[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...",[Sam Mendes]
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...",[Christopher Nolan]
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...",[Andrew Stanton]
...,...,...,...,...,...,...,...
4803,9367,El Mariachi,"[El, Mariachi, just, wants, to, play, his, gui...","[Action, Crime, Thriller]","[united statesâ€“mexico barrier, legs, arms, pap...","[{""cast_id"": 1, ""character"": ""El Mariachi"", ""c...",[Robert Rodriguez]
4804,72766,Newlyweds,"[A, newlywed, couple's, honeymoon, is, upended...","[Comedy, Romance]",[],"[{""cast_id"": 1, ""character"": ""Buzzy"", ""credit_...",[Edward Burns]
4805,231617,"Signed, Sealed, Delivered","[""Signed,, Sealed,, Delivered"", introduces, a,...","[Comedy, Drama, Romance, TV Movie]","[date, love at first sight, narration, investi...","[{""cast_id"": 8, ""character"": ""Oliver O\u2019To...",[Scott Smith]
4806,126186,Shanghai Calling,"[When, ambitious, New, York, attorney, Sam, is...",[],[],"[{""cast_id"": 3, ""character"": ""Sam"", ""credit_id...",[Daniel Hsia]
4807,25975,My Date with Drew,"[Ever, since, the, second, grade, when, he, fi...",[Documentary],"[obsession, camcorder, crush, dream girl]","[{""cast_id"": 3, ""character"": ""Herself"", ""credi...","[Brian Herzlinger, Jon Gunn, Brett Winn]"

In [152]:
movies_df['genres']=movies_df['genres'].apply(lambda x:[i.replace(" ","") for i in x])
movies_df['keywords']=movies_df['keywords'].apply(lambda x:[i.replace(" ","") for i in x])
movies_df['cast']=movies_df['cast'].apply(lambda x:[i.replace(" ","") for i in x])
movies_df['crew']=movies_df['crew'].apply(lambda x:[i.replace(" ","") for i in x])

In [153]:
movies_df

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[[, {, "", c, a, s, t, _, i, d, "", :, , 2, 4, 2...",[JamesCameron]
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad...","[[, {, "", c, a, s, t, _, i, d, "", :, , 4, ,, ,...",[GoreVerbinski]
2,206647,Spectre,"[A, cryptic, message, from, Bondâ€™s, past, send...","[Action, Adventure, Crime]","[spy, basedonnovel, secretagent, sequel, mi6, ...","[[, {, "", c, a, s, t, _, i, d, "", :, , 1, ,, ,...",[SamMendes]
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dccomics, crimefighter, terrorist, secretiden...","[[, {, "", c, a, s, t, _, i, d, "", :, , 2, ,, ,...",[ChristopherNolan]
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, ScienceFiction]","[basedonnovel, mars, medallion, spacetravel, p...","[[, {, "", c, a, s, t, _, i, d, "", :, , 5, ,, ,...",[AndrewStanton]
...,...,...,...,...,...,...,...
4803,9367,El Mariachi,"[El, Mariachi, just, wants, to, play, his, gui...","[Action, Crime, Thriller]","[unitedstatesâ€“mexicobarrier, legs, arms, paper...","[[, {, "", c, a, s, t, _, i, d, "", :, , 1, ,, ,...",[RobertRodriguez]
4804,72766,Newlyweds,"[A, newlywed, couple's, honeymoon, is, upended...","[Comedy, Romance]",[],"[[, {, "", c, a, s, t, _, i, d, "", :, , 1, ,, ,...",[EdwardBurns]
4805,231617,"Signed, Sealed, Delivered","[""Signed,, Sealed,, Delivered"", introduces, a,...","[Comedy, Drama, Romance, TVMovie]","[date, loveatfirstsight, narration, investigat...","[[, {, "", c, a, s, t, _, i, d, "", :, , 8, ,, ,...",[ScottSmith]
4806,126186,Shanghai Calling,"[When, ambitious, New, York, attorney, Sam, is...",[],[],"[[, {, "", c, a, s, t, _, i, d, "", :, , 3, ,, ,...",[DanielHsia]
4807,25975,My Date with Drew,"[Ever, since, the, second, grade, when, he, fi...",[Documentary],"[obsession, camcorder, crush, dreamgirl]","[[, {, "", c, a, s, t, _, i, d, "", :, , 3, ,, ,...","[BrianHerzlinger, JonGunn, BrettWinn]"

In [154]:
movies_df['tags']=movies_df['overview']+movies_df['genres']+movies_df['keywords']+movies_df['cast']+movies_df['crew']

In [155]:
movies_df

,movie_id,title,overview,genres,keywords,cast,crew,tags
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[[, {, "", c, a, s, t, _, i, d, "", :, , 2, 4, 2...",[JamesCameron],"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad...","[[, {, "", c, a, s, t, _, i, d, "", :, , 4, ,, ,...",[GoreVerbinski],"[Captain, Barbossa,, long, believed, to, be, d..."
2,206647,Spectre,"[A, cryptic, message, from, Bondâ€™s, past, send...","[Action, Adventure, Crime]","[spy, basedonnovel, secretagent, sequel, mi6, ...","[[, {, "", c, a, s, t, _, i, d, "", :, , 1, ,, ,...",[SamMendes],"[A, cryptic, message, from, Bondâ€™s, past, send..."
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dccomics, crimefighter, terrorist, secretiden...","[[, {, "", c, a, s, t, _, i, d, "", :, , 2, ,, ,...",[ChristopherNolan],"[Following, the, death, of, District, Attorney..."
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, ScienceFiction]","[basedonnovel, mars, medallion, spacetravel, p...","[[, {, "", c, a, s, t, _, i, d, "", :, , 5, ,, ,...",[AndrewStanton],"[John, Carter, is, a, war-weary,, former, mili..."
...,...,...,...,...,...,...,...,...
4803,9367,El Mariachi,"[El, Mariachi, just, wants, to, play, his, gui...","[Action, Crime, Thriller]","[unitedstatesâ€“mexicobarrier, legs, arms, paper...","[[, {, "", c, a, s, t, _, i, d, "", :, , 1, ,, ,...",[RobertRodriguez],"[El, Mariachi, just, wants, to, play, his, gui..."
4804,72766,Newlyweds,"[A, newlywed, couple's, honeymoon, is, upended...","[Comedy, Romance]",[],"[[, {, "", c, a, s, t, _, i, d, "", :, , 1, ,, ,...",[EdwardBurns],"[A, newlywed, couple's, honeymoon, is, upended..."
4805,231617,"Signed, Sealed, Delivered","[""Signed,, Sealed,, Delivered"", introduces, a,...","[Comedy, Drama, Romance, TVMovie]","[date, loveatfirstsight, narration, investigat...","[[, {, "", c, a, s, t, _, i, d, "", :, , 8, ,, ,...",[ScottSmith],"[""Signed,, Sealed,, Delivered"", introduces, a,..."
4806,126186,Shanghai Calling,"[When, ambitious, New, York, attorney, Sam, is...",[],[],"[[, {, "", c, a, s, t, _, i, d, "", :, , 3, ,, ,...",[DanielHsia],"[When, ambitious, New, York, attorney, Sam, is..."
4807,25975,My Date with Drew,"[Ever, since, the, second, grade, when, he, fi...",[Documentary],"[obsession, camcorder, crush, dreamgirl]","[[, {, "", c, a, s, t, _, i, d, "", :, , 3, ,, ,...","[BrianHerzlinger, JonGunn, BrettWinn]","[Ever, since, the, second, grade, when, he, fi..."

In [156]:
new_df=movies_df[['movie_id','title','tags']]

In [157]:
new_df

,movie_id,title,tags
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d..."
2,206647,Spectre,"[A, cryptic, message, from, Bondâ€™s, past, send..."
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney..."
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili..."
...,...,...,...
4803,9367,El Mariachi,"[El, Mariachi, just, wants, to, play, his, gui..."
4804,72766,Newlyweds,"[A, newlywed, couple's, honeymoon, is, upended..."
4805,231617,"Signed, Sealed, Delivered","[""Signed,, Sealed,, Delivered"", introduces, a,..."
4806,126186,Shanghai Calling,"[When, ambitious, New, York, attorney, Sam, is..."
4807,25975,My Date with Drew,"[Ever, since, the, second, grade, when, he, fi..."

In [158]:
new_df['tags']=new_df['tags'].apply(lambda x:' '.join(x))

C:\Users\HP\AppData\Local\Temp\ipykernel_7976\218205508.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags']=new_df['tags'].apply(lambda x:' '.join(x))

In [159]:
new_df

,movie_id,title,tags
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha..."
2,206647,Spectre,A cryptic message from Bondâ€™s past sends him o...
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...
4,49529,John Carter,"John Carter is a war-weary, former military ca..."
...,...,...,...
4803,9367,El Mariachi,El Mariachi just wants to play his guitar and ...
4804,72766,Newlyweds,A newlywed couple's honeymoon is upended by th...
4805,231617,"Signed, Sealed, Delivered","""Signed, Sealed, Delivered"" introduces a dedic..."
4806,126186,Shanghai Calling,When ambitious New York attorney Sam is sent t...
4807,25975,My Date with Drew,Ever since the second grade when he first saw ...

In [160]:
new_df['tags'][0]

'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization. Action Adventure Fantasy ScienceFiction cultureclash future spacewar spacecolony society spacetravel futuristic romance space alien tribe alienplanet cgi marine soldier battle loveaffair antiwar powerrelations mindandsoul 3d [ { " c a s t _ i d " :  2 4 2 ,  " c h a r a c t e r " :  " J a k e  S u l l y " ,  " c r e d i t _ i d " :  " 5 6 0 2 a 8 a 7 c 3 a 3 6 8 5 5 3 2 0 0 1 c 9 a " ,  " g e n d e r " :  2 ,  " i d " :  6 5 7 3 1 ,  " n a m e " :  " S a m  W o r t h i n g t o n " ,  " o r d e r " :  0 } ,  { " c a s t _ i d " :  3 ,  " c h a r a c t e r " :  " N e y t i r i " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c 9 c b " ,  " g e n d e r " :  1 ,  " i d " :  8 6 9 1 ,  " n a m e " :  " Z o e  S a l d a n a " ,  " o r d e r " :  1 } ,  { " c a s t _ i d " :  2 5 ,  " c h a r a c t e r " :  " D r .  G r a c e  A u g u s t i n e " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 3 9 " ,  " g e n d e r " :  1 ,  " i d " :  1 0 2 0 5 ,  " n a m e " :  " S i g o u r n e y  W e a v e r " ,  " o r d e r " :  2 } ,  { " c a s t _ i d " :  4 ,  " c h a r a c t e r " :  " C o l .  Q u a r i t c h " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c 9 c f " ,  " g e n d e r " :  2 ,  " i d " :  3 2 7 4 7 ,  " n a m e " :  " S t e p h e n  L a n g " ,  " o r d e r " :  3 } ,  { " c a s t _ i d " :  5 ,  " c h a r a c t e r " :  " T r u d y  C h a c o n " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c 9 d 3 " ,  " g e n d e r " :  1 ,  " i d " :  1 7 6 4 7 ,  " n a m e " :  " M i c h e l l e  R o d r i g u e z " ,  " o r d e r " :  4 } ,  { " c a s t _ i d " :  8 ,  " c h a r a c t e r " :  " S e l f r i d g e " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c 9 e 1 " ,  " g e n d e r " :  2 ,  " i d " :  1 7 7 1 ,  " n a m e " :  " G i o v a n n i  R i b i s i " ,  " o r d e r " :  5 } ,  { " c a s t _ i d " :  7 ,  " c h a r a c t e r " :  " N o r m  S p e l l m a n " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c 9 d d " ,  " g e n d e r " :  2 ,  " i d " :  5 9 2 3 1 ,  " n a m e " :  " J o e l  D a v i d  M o o r e " ,  " o r d e r " :  6 } ,  { " c a s t _ i d " :  9 ,  " c h a r a c t e r " :  " M o a t " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c 9 e 5 " ,  " g e n d e r " :  1 ,  " i d " :  3 0 4 8 5 ,  " n a m e " :  " C C H  P o u n d e r " ,  " o r d e r " :  7 } ,  { " c a s t _ i d " :  1 1 ,  " c h a r a c t e r " :  " E y t u k a n " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c 9 e d " ,  " g e n d e r " :  2 ,  " i d " :  1 5 8 5 3 ,  " n a m e " :  " W e s  S t u d i " ,  " o r d e r " :  8 } ,  { " c a s t _ i d " :  1 0 ,  " c h a r a c t e r " :  " T s u \' T e y " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c 9 e 9 " ,  " g e n d e r " :  2 ,  " i d " :  1 0 9 6 4 ,  " n a m e " :  " L a z  A l o n s o " ,  " o r d e r " :  9 } ,  { " c a s t _ i d " :  1 2 ,  " c h a r a c t e r " :  " D r .  M a x  P a t e l " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c 9 f 1 " ,  " g e n d e r " :  2 ,  " i d " :  9 5 6 9 7 ,  " n a m e " :  " D i l e e p  R a o " ,  " o r d e r " :  1 0 } ,  { " c a s t _ i d " :  1 3 ,  " c h a r a c t e r " :  " L y l e  W a i n f l e e t " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c 9 f 5 " ,  " g e n d e r " :  2 ,  " i d " :  9 8 2 1 5 ,  " n a m e " :  " M a t t  G e r a l d " ,  " o r d e r " :  1 1 } ,  { " c a s t _ i d " :  3 2 ,  " c h a r a c t e r " :  " P r i v a t e  F i k e " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 5 b " ,  " g e n d e r " :  2 ,  " i d " :  1 5 4 1 5 3 ,  " n a m e " :  " S e a n  A n t h o n y  M o r a n " ,  " o r d e r " :  1 2 } ,  { " c a s t _ i d " :  3 3 ,  " c h a r a c t e r " :  " C r y o  V a u l t  M e d  T e c h " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 5 f " ,  " g e n d e r " :  2 ,  " i d " :  3 9 7 3 1 2 ,  " n a m e " :  " J a s o n  W h y t e " ,  " o r d e r " :  1 3 } ,  { " c a s t _ i d " :  3 4 ,  " c h a r a c t e r " :  " V e n t u r e  S t a r  C r e w  C h i e f " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 6 3 " ,  " g e n d e r " :  2 ,  " i d " :  4 2 3 1 7 ,  " n a m e " :  " S c o t t  L a w r e n c e " ,  " o r d e r " :  1 4 } ,  { " c a s t _ i d " :  3 5 ,  " c h a r a c t e r " :  " L o c k  U p  T r o o p e r " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 6 7 " ,  " g e n d e r " :  2 ,  " i d " :  9 8 6 7 3 4 ,  " n a m e " :  " K e l l y  K i l g o u r " ,  " o r d e r " :  1 5 } ,  { " c a s t _ i d " :  3 6 ,  " c h a r a c t e r " :  " S h u t t l e  P i l o t " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 6 b " ,  " g e n d e r " :  0 ,  " i d " :  1 2 0 7 2 2 7 ,  " n a m e " :  " J a m e s  P a t r i c k  P i t t " ,  " o r d e r " :  1 6 } ,  { " c a s t _ i d " :  3 7 ,  " c h a r a c t e r " :  " S h u t t l e  C o - P i l o t " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 6 f " ,  " g e n d e r " :  0 ,  " i d " :  1 1 8 0 9 3 6 ,  " n a m e " :  " S e a n  P a t r i c k  M u r p h y " ,  " o r d e r " :  1 7 } ,  { " c a s t _ i d " :  3 8 ,  " c h a r a c t e r " :  " S h u t t l e  C r e w  C h i e f " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 7 3 " ,  " g e n d e r " :  2 ,  " i d " :  1 0 1 9 5 7 8 ,  " n a m e " :  " P e t e r  D i l l o n " ,  " o r d e r " :  1 8 } ,  { " c a s t _ i d " :  3 9 ,  " c h a r a c t e r " :  " T r a c t o r  O p e r a t o r  /  T r o u p e " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 7 7 " ,  " g e n d e r " :  0 ,  " i d " :  9 1 4 4 3 ,  " n a m e " :  " K e v i n  D o r m a n " ,  " o r d e r " :  1 9 } ,  { " c a s t _ i d " :  4 0 ,  " c h a r a c t e r " :  " D r a g o n  G u n s h i p  P i l o t " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 7 b " ,  " g e n d e r " :  2 ,  " i d " :  1 7 3 3 9 1 ,  " n a m e " :  " K e l s o n  H e n d e r s o n " ,  " o r d e r " :  2 0 } ,  { " c a s t _ i d " :  4 1 ,  " c h a r a c t e r " :  " D r a g o n  G u n s h i p  G u n n e r " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 7 f " ,  " g e n d e r " :  0 ,  " i d " :  1 2 0 7 2 3 6 ,  " n a m e " :  " D a v i d  V a n  H o r n " ,  " o r d e r " :  2 1 } ,  { " c a s t _ i d " :  4 2 ,  " c h a r a c t e r " :  " D r a g o n  G u n s h i p  N a v i g a t o r " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 8 3 " ,  " g e n d e r " :  0 ,  " i d " :  2 1 5 9 1 3 ,  " n a m e " :  " J a c o b  T o m u r i " ,  " o r d e r " :  2 2 } ,  { " c a s t _ i d " :  4 3 ,  " c h a r a c t e r " :  " S u i t  # 1 " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 8 7 " ,  " g e n d e r " :  0 ,  " i d " :  1 4 3 2 0 6 ,  " n a m e " :  " M i c h a e l  B l a i n - R o z g a y " ,  " o r d e r " :  2 3 } ,  { " c a s t _ i d " :  4 4 ,  " c h a r a c t e r " :  " S u i t  # 2 " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 8 b " ,  " g e n d e r " :  2 ,  " i d " :  1 6 9 6 7 6 ,  " n a m e " :  " J o n  C u r r y " ,  " o r d e r " :  2 4 } ,  { " c a s t _ i d " :  4 6 ,  " c h a r a c t e r " :  " A m b i e n t  R o o m  T e c h " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 8 f " ,  " g e n d e r " :  0 ,  " i d " :  1 0 4 8 6 1 0 ,  " n a m e " :  " L u k e  H a w k e r " ,  " o r d e r " :  2 5 } ,  { " c a s t _ i d " :  4 7 ,  " c h a r a c t e r " :  " A m b i e n t  R o o m  T e c h  /  T r o u p e " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 9 3 " ,  " g e n d e r " :  0 ,  " i d " :  4 2 2 8 8 ,  " n a m e " :  " W o o d y  S c h u l t z " ,  " o r d e r " :  2 6 } ,  { " c a s t _ i d " :  4 8 ,  " c h a r a c t e r " :  " H o r s e  C l a n  L e a d e r " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 9 7 " ,  " g e n d e r " :  2 ,  " i d " :  6 8 2 7 8 ,  " n a m e " :  " P e t e r  M e n s a h " ,  " o r d e r " :  2 7 } ,  { " c a s t _ i d " :  4 9 ,  " c h a r a c t e r " :  " L i n k  R o o m  T e c h " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 9 b " ,  " g e n d e r " :  0 ,  " i d " :  1 2 0 7 2 4 7 ,  " n a m e " :  " S o n i a  Y e e " ,  " o r d e r " :  2 8 } ,  { " c a s t _ i d " :  5 0 ,  " c h a r a c t e r " :  " B a s k e t b a l l  A v a t a r  /  T r o u p e " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 9 f " ,  " g e n d e r " :  1 ,  " i d " :  1 2 0 7 2 4 8 ,  " n a m e " :  " J a h n e l  C u r f m a n " ,  " o r d e r " :  2 9 } ,  { " c a s t _ i d " :  5 1 ,  " c h a r a c t e r " :  " B a s k e t b a l l  A v a t a r " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a a 3 " ,  " g e n d e r " :  0 ,  " i d " :  8 9 7 1 4 ,  " n a m e " :  " I l r a m  C h o i " ,  " o r d e r " :  3 0 } ,  { " c a s t _ i d " :  5 2 ,  " c h a r a c t e r " :  " N a \' v i  C h i l d " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a a 7 " ,  " g e n d e r " :  0 ,  " i d " :  1 2 0 7 2 4 9 ,  " n a m e " :  " K y l a  W a r r e n " ,  " o r d e r " :  3 1 } ,  { " c a s t _ i d " :  5 3 ,  " c h a r a c t e r " :  " T r o u p e " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a a b " ,  " g e n d e r " :  0 ,  " i d " :  1 2 0 7 2 5 0 ,  " n a m e " :  " L i s a  R o u m a i n " ,  " o r d e r " :  3 2 } ,  { " c a s t _ i d " :  5 4 ,  " c h a r a c t e r " :  " T r o u p e " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a a f " ,  " g e n d e r " :  1 ,  " i d " :  8 3 1 0 5 ,  " n a m e " :  " D e b r a  W i l s o n " ,  " o r d e r " :  3 3 } ,  { " c a s t _ i d " :  5 7 ,  " c h a r a c t e r " :  " T r o u p e " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a b b " ,  " g e n d e r " :  0 ,  " i d " :  1 2 0 7 2 5 3 ,  " n a m e " :  " C h r i s  M a l a " ,  " o r d e r " :  3 4 } ,  { " c a s t _ i d " :  5 5 ,  " c h a r a c t e r " :  " T r o u p e " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a b 3 " ,  " g e n d e r " :  0 ,  " i d " :  1 2 0 7 2 5 1 ,  " n a m e " :  " T a y l o r  K i b b y " ,  " o r d e r " :  3 5 } ,  { " c a s t _ i d " :  5 6 ,  " c h a r a c t e r " :  " T r o u p e " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a b 7 " ,  " g e n d e r " :  0 ,  " i d " :  1 2 0 7 2 5 2 ,  " n a m e " :  " J o d i e  L a n d a u " ,  " o r d e r " :  3 6 } ,  { " c a s t _ i d " :  5 8 ,  " c h a r a c t e r " :  " T r o u p e " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a b f " ,  " g e n d e r " :  0 ,  " i d " :  1 2 0 7 2 5 4 ,  " n a m e " :  " J u l i e  L a m m " ,  " o r d e r " :  3 7 } ,  { " c a s t _ i d " :  5 9 ,  " c h a r a c t e r " :  " T r o u p e " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a c 3 " ,  " g e n d e r " :  0 ,  " i d " :  1 2 0 7 2 5 7 ,  " n a m e " :  " C u l l e n  B .  M a d d e n " ,  " o r d e r " :  3 8 } ,  { " c a s t _ i d " :  6 0 ,  " c h a r a c t e r " :  " T r o u p e " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a c 7 " ,  " g e n d e r " :  0 ,  " i d " :  1 2 0 7 2 5 9 ,  " n a m e " :  " J o s e p h  B r a d y  M a d d e n " ,  " o r d e r " :  3 9 } ,  { " c a s t _ i d " :  6 1 ,  " c h a r a c t e r " :  " T r o u p e " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a c b " ,  " g e n d e r " :  0 ,  " i d " :  1 2 0 7 2 6 2 ,  " n a m e " :  " F r a n k i e  T o r r e s " ,  " o r d e r " :  4 0 } ,  { " c a s t _ i d " :  6 2 ,  " c h a r a c t e r " :  " T r o u p e " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a c f " ,  " g e n d e r " :  1 ,  " i d " :  1 1 5 8 6 0 0 ,  " n a m e " :  " A u s t i n  W i l s o n " ,  " o r d e r " :  4 1 } ,  { " c a s t _ i d " :  6 3 ,  " c h a r a c t e r " :  " T r o u p e " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c a d 3 " ,  " g e n d e r " :  1 ,  " i d " :  9 8 3 7 0 5 ,  " n a m e " :  " S a r a  W i l s o n " ,  " o r d e r " :  4 2 } ,  { " c a s t _ i d " :  6 4 ,  " c h a r a c t e r " :  " T r o u p e " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c a d 7 " ,  " g e n d e r " :  0 ,  " i d " :  1 2 0 7 2 6 3 ,  " n a m e " :  " T a m i c a  W a s h i n g t o n - M i l l e r " ,  " o r d e r " :  4 3 } ,  { " c a s t _ i d " :  6 5 ,  " c h a r a c t e r " :  " O p  C e n t e r  S t a f f " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c a d b " ,  " g e n d e r " :  1 ,  " i d " :  1 1 4 5 0 9 8 ,  " n a m e " :  " L u c y  B r i a n t " ,  " o r d e r " :  4 4 } ,  { " c a s t _ i d " :  6 6 ,  " c h a r a c t e r " :  " O p  C e n t e r  S t a f f " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c a d f " ,  " g e n d e r " :  2 ,  " i d " :  3 3 3 0 5 ,  " n a m e " :  " N a t h a n  M e i s t e r " ,  " o r d e r " :  4 5 } ,  { " c a s t _ i d " :  6 7 ,  " c h a r a c t e r " :  " O p  C e n t e r  S t a f f " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c a e 3 " ,  " g e n d e r " :  0 ,  " i d " :  1 2 0 7 2 6 4 ,  " n a m e " :  " G e r r y  B l a i r " ,  " o r d e r " :  4 6 } ,  { " c a s t _ i d " :  6 8 ,  " c h a r a c t e r " :  " O p  C e n t e r  S t a f f " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c a e 7 " ,  " g e n d e r " :  2 ,  " i d " :  3 3 3 1 1 ,  " n a m e " :  " M a t t h e w  C h a m b e r l a i n " ,  " o r d e r " :  4 7 } ,  { " c a s t _ i d " :  6 9 ,  " c h a r a c t e r " :  " O p  C e n t e r  S t a f f " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c a e b " ,  " g e n d e r " :  0 ,  " i d " :  1 2 0 7 2 6 5 ,  " n a m e " :  " P a u l  Y a t e s " ,  " o r d e r " :  4 8 } ,  { " c a s t _ i d " :  7 0 ,  " c h a r a c t e r " :  " O p  C e n t e r  D u t y  O f f i c e r " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c a e f " ,  " g e n d e r " :  0 ,  " i d " :  1 2 0 7 2 6 6 ,  " n a m e " :  " W r a y  W i l s o n " ,  " o r d e r " :  4 9 } ,  { " c a s t _ i d " :  7 1 ,  " c h a r a c t e r " :  " O p  C e n t e r  S t a f f " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c a f 3 " ,  " g e n d e r " :  2 ,  " i d " :  5 4 4 9 2 ,  " n a m e " :  " J a m e s  G a y l y n " ,  " o r d e r " :  5 0 } ,  { " c a s t _ i d " :  7 2 ,  " c h a r a c t e r " :  " D a n c e r " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c a f 7 " ,  " g e n d e r " :  0 ,  " i d " :  1 2 0 7 2 6 7 ,  " n a m e " :  " M e l v i n  L e n o  C l a r k  I I I " ,  " o r d e r " :  5 1 } ,  { " c a s t _ i d " :  7 3 ,  " c h a r a c t e r " :  " D a n c e r " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c a f b " ,  " g e n d e r " :  0 ,  " i d " :  1 2 0 7 2 6 8 ,  " n a m e " :  " C a r v o n  F u t r e l l " ,  " o r d e r " :  5 2 } ,  { " c a s t _ i d " :  7 4 ,  " c h a r a c t e r " :  " D a n c e r " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c a f f " ,  " g e n d e r " :  0 ,  " i d " :  1 2 0 7 2 6 9 ,  " n a m e " :  " B r a n d o n  J e l k e s " ,  " o r d e r " :  5 3 } ,  { " c a s t _ i d " :  7 5 ,  " c h a r a c t e r " :  " D a n c e r " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c b 0 3 " ,  " g e n d e r " :  0 ,  " i d " :  1 2 0 7 2 7 0 ,  " n a m e " :  " M i c a h  M o c h " ,  " o r d e r " :  5 4 } ,  { " c a s t _ i d " :  7 6 ,  " c h a r a c t e r " :  " D a n c e r " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c b 0 7 " ,  " g e n d e r " :  0 ,  " i d " :  1 2 0 7 2 7 1 ,  " n a m e " :  " H a n n i y a h  M u h a m m a d " ,  " o r d e r " :  5 5 } ,  { " c a s t _ i d " :  7 7 ,  " c h a r a c t e r " :  " D a n c e r " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c b 0 b " ,  " g e n d e r " :  0 ,  " i d " :  1 2 0 7 2 7 2 ,  " n a m e " :  " C h r i s t o p h e r  N o l e n " ,  " o r d e r " :  5 6 } ,  { " c a s t _ i d " :  7 8 ,  " c h a r a c t e r " :  " D a n c e r " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c b 0 f " ,  " g e n d e r " :  0 ,  " i d " :  1 2 0 7 2 7 3 ,  " n a m e " :  " C h r i s t a  O l i v e r " ,  " o r d e r " :  5 7 } ,  { " c a s t _ i d " :  7 9 ,  " c h a r a c t e r " :  " D a n c e r " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c b 1 3 " ,  " g e n d e r " :  0 ,  " i d " :  1 2 0 7 2 7 4 ,  " n a m e " :  " A p r i l  M a r i e  T h o m a s " ,  " o r d e r " :  5 8 } ,  { " c a s t _ i d " :  8 0 ,  " c h a r a c t e r " :  " D a n c e r " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c b 1 7 " ,  " g e n d e r " :  0 ,  " i d " :  1 2 0 7 2 7 5 ,  " n a m e " :  " B r a v i t a  A .  T h r e a t t " ,  " o r d e r " :  5 9 } ,  { " c a s t _ i d " :  8 1 ,  " c h a r a c t e r " :  " M i n i n g  C h i e f  ( u n c r e d i t e d ) " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c b 1 b " ,  " g e n d e r " :  0 ,  " i d " :  1 2 0 7 2 7 6 ,  " n a m e " :  " C o l i n  B l e a s d a l e " ,  " o r d e r " :  6 0 } ,  { " c a s t _ i d " :  8 2 ,  " c h a r a c t e r " :  " V e t e r a n  M i n e r  ( u n c r e d i t e d ) " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c b 1 f " ,  " g e n d e r " :  0 ,  " i d " :  1 0 7 9 6 9 ,  " n a m e " :  " M i k e  B o d n a r " ,  " o r d e r " :  6 1 } ,  { " c a s t _ i d " :  8 3 ,  " c h a r a c t e r " :  " R i c h a r d  ( u n c r e d i t e d ) " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c b 2 3 " ,  " g e n d e r " :  0 ,  " i d " :  1 2 0 7 2 7 8 ,  " n a m e " :  " M a t t  C l a y t o n " ,  " o r d e r " :  6 2 } ,  { " c a s t _ i d " :  8 4 ,  " c h a r a c t e r " :  " N a v \' i  ( u n c r e d i t e d ) " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c b 2 7 " ,  " g e n d e r " :  1 ,  " i d " :  1 4 7 8 9 8 ,  " n a m e " :  " N i c o l e  D i o n n e " ,  " o r d e r " :  6 3 } ,  { " c a s t _ i d " :  8 5 ,  " c h a r a c t e r " :  " T r o o p e r  ( u n c r e d i t e d ) " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c b 2 b " ,  " g e n d e r " :  0 ,  " i d " :  1 2 0 7 2 8 0 ,  " n a m e " :  " J a m i e  H a r r i s o n " ,  " o r d e r " :  6 4 } ,  { " c a s t _ i d " :  8 6 ,  " c h a r a c t e r " :  " T r o o p e r  ( u n c r e d i t e d ) " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c b 2 f " ,  " g e n d e r " :  0 ,  " i d " :  1 2 0 7 2 8 1 ,  " n a m e " :  " A l l a n  H e n r y " ,  " o r d e r " :  6 5 } ,  { " c a s t _ i d " :  8 7 ,  " c h a r a c t e r " :  " G r o u n d  T e c h n i c i a n  ( u n c r e d i t e d ) " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c b 3 3 " ,  " g e n d e r " :  2 ,  " i d " :  1 2 0 7 2 8 2 ,  " n a m e " :  " A n t h o n y  I n g r u b e r " ,  " o r d e r " :  6 6 } ,  { " c a s t _ i d " :  8 8 ,  " c h a r a c t e r " :  " F l i g h t  C r e w  M e c h a n i c  ( u n 

In [161]:
new_df['tags']=new_df['tags'].apply(lambda x:x.lower())

C:\Users\HP\AppData\Local\Temp\ipykernel_7976\4224080999.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags']=new_df['tags'].apply(lambda x:x.lower())

In [162]:
new_df.head()

,movie_id,title,tags
0,19995,Avatar,"in the 22nd century, a paraplegic marine is di..."
1,285,Pirates of the Caribbean: At World's End,"captain barbossa, long believed to be dead, ha..."
2,206647,Spectre,a cryptic message from bondâ€™s past sends him o...
3,49026,The Dark Knight Rises,following the death of district attorney harve...
4,49529,John Carter,"john carter is a war-weary, former military ca..."

In [163]:
from sklearn.feature_extraction.text import CountVectorizer
cv= CountVectorizer(max_features=5000,stop_words='english')

In [164]:
cv.fit_transform(new_df['tags']).toarray().shape

(4805, 5000)

In [165]:
vectors = cv.fit_transform(new_df['tags']).toarray()

In [166]:
vectors[0]

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [167]:
len(cv.get_feature_names_out())

5000

In [168]:
import nltk

In [169]:
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()

In [170]:
def stem(text):
    y=[]
    for i in text.split():
        y.append(ps.stem(i))
    return " ".join(y)

In [171]:
new_df['tags']=new_df['tags'].apply(stem)

C:\Users\HP\AppData\Local\Temp\ipykernel_7976\3514595201.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags']=new_df['tags'].apply(stem)

In [172]:
from sklearn.metrics.pairwise import cosine_similarity

In [173]:
cosine_similarity(vectors)

array([[1.        , 0.09284767, 0.06085806, ..., 0.02431083, 0.02635231,
        0.        ],
       [0.09284767, 1.        , 0.06780635, ..., 0.02708645, 0.        ,
        0.        ],
       [0.06085806, 0.06780635, 1.        , ..., 0.02663118, 0.        ,
        0.        ],
       ...,
       [0.02431083, 0.02708645, 0.02663118, ..., 1.        , 0.06918984,
        0.04732485],
       [0.02635231, 0.        , 0.        , ..., 0.06918984, 1.        ,
        0.05129892],
       [0.        , 0.        , 0.        , ..., 0.04732485, 0.05129892,
        1.        ]])

In [174]:
cosine_similarity(vectors).shape

(4805, 4805)

In [175]:
similarity = cosine_similarity(vectors)

In [176]:
similarity[0]

array([1.        , 0.09284767, 0.06085806, ..., 0.02431083, 0.02635231,
       0.        ])

In [177]:
similarity[0].shape

(4805,)

In [178]:
sorted(list(enumerate(similarity[0])), reverse = True,key = lambda x:x[1])[1:6]

[(539, 0.26940795304016235),
 (1194, 0.2545875386086578),
 (507, 0.2518277005725965),
 (1216, 0.24459979523511427),
 (260, 0.2434322477800738)]

In [179]:
def recommend(movie):
    movei_index = new_df[new_df['title']==movie].index[0]
    distances=similarity[movei_index]
    movies_list = sorted(list(enumerate(distances)),reverse=True,key=lambda x:x[1])[1:6]
    for i in movies_list:
        print(new_df.iloc[i[0]].title)

In [180]:
recommend('Avatar')

Titan A.E.
Small Soldiers
Independence Day
Aliens vs Predator: Requiem
Ender's Game

In [181]:
recommend('Iron Man')

Iron Man 2
Iron Man 3
Avengers: Age of Ultron
Ant-Man
X-Men

In [182]:
recommend('Iron Man 3')

Iron Man
Iron Man 2
Avengers: Age of Ultron
X-Men
Captain America: Civil War